backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page'
            }
          - {
              label: Logos,
              name: logos,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Alt, name: alt, widget: string },
                  { label: Link, name: link, widget: string }
                ]
            }
          - {
              label: Me,
              name: me,
              widget: object,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Link, name: link, widget: string }
                ]
            }
          - {
              label: Inspiration,
              name: inspiration,
              widget: object,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Link, name: link, widget: string }
                ]
            }
